### ISSUE TITLE
Fix image scaling on AWS Summit post

### ISSUE THREAD

**Issue by michaelwnau** [zCoreGroup/zcoregroup.github.io#103]
EDIT: Solution was just adding an eklement class in the steylesheet. See below.

It wasn't apparent in the thumbnail preview in the PR but the images need to be scaled down significantly. 

Thoughts on this:

1. In _layouts, we can have a `post.html` and a `slider-post.html` (or whatever else) for single and for multi image blogs
2. Some blogs could be slide decks, different format
3. Constraining image dimensions in the template file, i.e "Design as Code"

**Comment by bastosmichael** [comment]
https://github.com/wildlyinaccurate/jekyll-responsive-image

**Comment by michaelwnau** [comment]
![Image](https://github.com/zCoreGroup/zcoregroup.github.io/assets/101219686/e2a67591-3bd6-46cf-be77-3f38d246fc44)
