### ISSUE TITLE
Write Solutions page copy

### ISSUE THREAD

**Issue by michaelwnau** [zCoreGroup/zcoregroup.github.io#73]

**Comment by bastosmichael** [comment]
https://github.com/zCoreGroup/zcoregroup.github.io/pull/150

https://github.com/zCoreGroup/zcoregroup.github.io/pull/149

https://github.com/zCoreGroup/zcoregroup.github.io/pull/148

https://github.com/zCoreGroup/zcoregroup.github.io/pull/147

https://github.com/zCoreGroup/zcoregroup.github.io/pull/146

https://github.com/zCoreGroup/zcoregroup.github.io/pull/145

https://github.com/zCoreGroup/zcoregroup.github.io/pull/141

PR's that completed ticket.
