### ISSUE TITLE
Fix Paginate- Blog post page 2

### ISSUE THREAD

**Issue by michaelwnau** [zCoreGroup/zcoregroup.github.io#85]
Fix pagination click through

Source: ./_includes/pagination.html  --> line 8, 13 

Checked in `post_loop_two` and `pagination` -- no errors orig there

See: https://github.com/sverrirs/jekyll-paginate-v2

**Comment by bastosmichael** [comment]
https://github.com/zCoreGroup/zcoregroup.github.io/pull/163
